version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cannacare_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_cannacare_2026
      POSTGRES_DB: cannacare_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
